# Generated by Django 4.1 on 2022-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario_cnab",
            name="cartao",
            field=models.CharField(max_length=50),
        ),
    ]
